name: "Kodeverse Bot"

on:
  push:
  schedule:
    - cron: "* * * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12
          - 14
          - 16
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules/
          # key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('package*.json') }}
      - run: npm ci --ignore-scripts
        - run: npm install
        - name: Bot
          run: echo ${{ secrets.TELEGRAM_BOT_API }}
        - name: Run server.js
          run: node server.js
          env:
            TELEGRAM_BOT_API: ${{ secrets.TELEGRAM_BOT_API }}
            # TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID  }}
